### ISSUE TITLE
use accurate clocks to measure time?

### ISSUE THREAD

**Issue by c-cube** [Chris00/ocaml-benchmark#9]
Possible options:

- ptime
- oclock
- some system clock (if we want to measure CPU usage instead of wall time?)

**Comment by Chris00** [comment]
Not sure I understand what you mean.  `Ptime` provides a way to represent the time (and time lapses) but no way to get it from the system.   CPU usage is contained in `Benchmark.t`.  `oclock` looks nice but should be added as an optional dependency to let the library run on non POSIX machines.

**Comment by c-cube** [comment]
I meant mtime, the monotonic clock. But indeed, if you measure CPU usage, it's fine, ignore me :-)
